# Generated by Django 5.2.3 on 2025-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_rename_assignee_id_task_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-do'), ('in-progress', 'In-progress'), ('review', 'Review'), ('done', 'Done')], default='to_do', max_length=50),
        ),
    ]
