# Generated by Django 5.2.3 on 2025-06-18 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the board', max_length=255, unique=True)),
                ('member_count', models.PositiveIntegerField(default=0, help_text='Number of members in the board')),
                ('ticket_count', models.PositiveIntegerField(default=0, help_text='Number of tickets to do')),
                ('tasks_to_do_count', models.PositiveIntegerField(default=0, help_text='Number of tasks to do')),
                ('tasks_hight_prio_count', models.PositiveIntegerField(default=0, help_text='Number of high priority tasks')),
                ('due_date', models.DateField(blank=True, help_text='Due date for the board tasks', null=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Users who are members of the board', related_name='board_members', to=settings.AUTH_USER_MODEL, verbose_name='users')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('rewiewers', models.ManyToManyField(blank=True, help_text='Users who can review tasks in the board', related_name='board_reviewers', to=settings.AUTH_USER_MODEL, verbose_name='reviewers')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['title'],
            },
        ),
    ]
