# Generated by Django 5.2.3 on 2025-06-18 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of the board', related_name='board_members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
