# Generated by Django 5.2.3 on 2025-07-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_alter_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
